#!/usr/bin/env python3
"""GTKWave session generator + checker for the per-test wave dumps (PLAN T7.1).

  wave_check.py gen                 (re)write dv/waves/<test>.gtkw for every test
  wave_check.py check <test> <vcd>  verify every signal in <test>.gtkw exists in
                                    the VCD and that the dump is not trivial
                                    (every listed signal is present; the key
                                    handshakes each change value at least once)

The dumps come from dv/waves/wave_dump.sv (WAVES=1): scopes <tb>, <tb>.dut and
<tb>.dut.u_ctrl, depth 1.  `make wave-<test>` runs the test with the dump, runs
`check`, then opens GTKWave if it is installed and a display is available.
If gtkwave and xvfb-run are installed, `check` also loads the session in a
headless GTKWave (gtkw_count.tcl) and requires it to resolve every trace;
otherwise that step is reported as skipped.
Exit status 1 on any missing signal / empty dump / unresolved trace.
"""
import os
import re
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))

# test -> (tb top module, dump path relative to the repo root)
TESTS = {
    "smoke": ("tb_smoke", "dv/iverilog/sim_build/smoke.vcd"),
    "tx":    ("tb_tx",    "dv/iverilog/sim_build/tx.vcd"),
    "loop":  ("tb_loop",  "dv/iverilog/sim_build/loop.vcd"),
    "pm":    ("tb_pm",    "dv/iverilog/sim_build/pm.vcd"),
    "rxovf": ("tb_rxovf", "dv/iverilog/sim_build/rxovf.vcd"),
    "scen":  ("tb_scen",  "dv/iverilog/sim_build/scen.vcd"),
    "upf":   ("tb_pipe7_upf_power", "lp/sim_build/upf_tb.vcd"),
}

# (group, [(signal-in-dut-scope, width)])
DUT_GROUPS = [
    ("Ethernet Tx (eth_clk)", [("eth_clk", 1), ("eth_rst_n", 1), ("eth_tvalid", 1), ("eth_tready", 1),
                               ("eth_tlast", 1), ("eth_tkeep", 32), ("eth_tdata", 256)]),
    ("Ethernet Rx (eth_clk)", [("eth_rx_tvalid", 1), ("eth_rx_tready", 1), ("eth_rx_tlast", 1),
                               ("eth_rx_tuser", 8), ("eth_rx_tkeep", 32), ("eth_rx_tdata", 256)]),
    ("PIPE Tx / link (pclk)", [("pclk", 1), ("pipe_rst_n", 1), ("pipe_tx_data_valid", 1),
                               ("pipe_tx_start_block", 1), ("pipe_tx_data", 64), ("pipe_powerdown", 2),
                               ("pipe_rate", 3), ("pipe_width", 2), ("pipe_phy_status", 1)]),
    ("PIPE Rx (pclk)", [("pipe_rx_data_valid", 1), ("pipe_rx_start_block", 1), ("pipe_rx_data", 64),
                        ("pipe_rx_valid", 1), ("pipe_rx_elec_idle", 1)]),
    ("Message bus", [("pipe_m2p_msgbus", 8), ("pipe_p2m_msgbus", 8)]),
    ("Control plane", [("ctrl_state", 3), ("tx_en", 1), ("ingress_stop", 1), ("stp_s3", 1),
                       ("tx_idle", 1), ("rx_idle", 1), ("mb_busy", 1), ("pam4_wr", 1)]),
    ("CDC / Rx health", [("tx_fifo_full", 1), ("tx_fifo_empty", 1), ("rx_fifo_full", 1),
                         ("rx_fifo_empty", 1), ("rx_dropped_flits", 16), ("rx_aborted_frames", 16)]),
    ("CSR", [("csr_valid", 1), ("csr_write", 1), ("csr_addr", 8), ("csr_wdata", 32), ("csr_rdata", 32)]),
]
PMU_GROUP = ("PMU (DV-only, lp/pipe7_pmu.sv)", [("dp_pwr_en", 1), ("dp_iso_en", 1), ("dp_save", 1),
                                                 ("dp_restore", 1), ("dp_off", 1)])
# signals that must change value at least once in any meaningful dump
MUST_TOGGLE = ["eth_clk", "pclk", "pipe_rst_n", "pipe_powerdown", "ctrl_state"]


def groups_for(test):
    tb, _ = TESTS[test]
    out = [(g, [(f"{tb}.dut.{n}", w) for n, w in sigs]) for g, sigs in DUT_GROUPS]
    if test == "upf":
        out.append((PMU_GROUP[0], [(f"{tb}.{n}", w) for n, w in PMU_GROUP[1]]))
    return out


def gen():
    for test, (tb, dump) in TESTS.items():
        lines = [
            f"[*] GTKWave session for test '{test}' ({tb}); generated by dv/waves/wave_check.py gen",
            f"[*] open with: make wave-{test}   (or: gtkwave {dump} dv/waves/{test}.gtkw)",
            f'[dumpfile] "{dump}"',
            "[timestart] 0",
            "[size] 1600 900",
            "[sst_width] 260",
            "[signals_width] 300",
        ]
        for g, sigs in groups_for(test):
            lines += ["@200", f"-{g}"]
            for name, w in sigs:
                if w == 1:
                    lines += ["@28", name]
                else:
                    lines += ["@22", f"{name}[{w - 1}:0]"]
        with open(os.path.join(HERE, f"{test}.gtkw"), "w") as fh:
            fh.write("\n".join(lines) + "\n")
        print(f"wrote dv/waves/{test}.gtkw")
    return 0


def parse_vcd(path):
    """Return {hier.name: id} and {id: number of value changes} (header + body)."""
    scopes, ids, changes = [], {}, {}
    with open(path, "r", errors="replace") as fh:
        in_defs = True
        for line in fh:
            if in_defs:
                toks = line.split()
                if not toks:
                    continue
                if toks[0] == "$scope":
                    scopes.append(toks[2])
                elif toks[0] == "$upscope":
                    scopes.pop()
                elif toks[0] == "$var":
                    # $var <type> <size> <id> <ref> [range] $end
                    vid, ref = toks[3], toks[4]
                    ids[".".join(scopes + [ref])] = vid
                    changes.setdefault(vid, 0)
                elif toks[0] == "$enddefinitions":
                    in_defs = False
                continue
            c = line[:1]
            if c in "01xzXZ" and len(line) > 1:
                vid = line[1:].strip()
            elif c in "bBrR":
                parts = line.split()
                vid = parts[1] if len(parts) > 1 else None
            else:
                continue
            if vid in changes:
                changes[vid] += 1
    return ids, changes


def gtkw_signals(test):
    sigs = []
    with open(os.path.join(HERE, f"{test}.gtkw")) as fh:
        for line in fh:
            line = line.strip()
            if not line or line[0] in "[@-*":
                continue
            sigs.append(re.sub(r"\[\d+:\d+\]$", "", line))
    return sigs


def check(test, vcd):
    if test not in TESTS:
        print(f"wave_check: unknown test '{test}' (known: {', '.join(TESTS)})")
        return 1
    if not os.path.exists(vcd) or os.path.getsize(vcd) == 0:
        print(f"WAVE CHECK FAIL: no dump at {vcd}")
        return 1
    ids, changes = parse_vcd(vcd)
    missing = [s for s in gtkw_signals(test) if s not in ids]
    tb = TESTS[test][0]
    flat = [s for s in MUST_TOGGLE if changes.get(ids.get(f"{tb}.dut.{s}"), 0) < 2]
    for s in missing:
        print(f"  missing in dump: {s}")
    for s in flat:
        print(f"  never changes:   {tb}.dut.{s}")
    n = len(gtkw_signals(test))
    if missing or flat:
        print(f"WAVE CHECK FAIL: {test}: {len(missing)} missing, {len(flat)} flat of {n} session signals")
        return 1
    print(f"WAVE CHECK PASS: {test}: all {n} session signals present in {vcd} "
          f"({sum(changes.values())} value changes)")
    return gui_load(test, vcd, n)


def gui_load(test, vcd, nsig):
    """Load the session in headless GTKWave; every signal + group header must resolve."""
    if not (shutil.which("gtkwave") and shutil.which("xvfb-run")):
        print("  gtkwave load: SKIPPED (gtkwave / xvfb-run not installed)")
        return 0
    ngroups = sum(1 for line in open(os.path.join(HERE, f"{test}.gtkw")) if line.startswith("-"))
    with tempfile.TemporaryDirectory() as td:
        out = os.path.join(td, "count.txt")
        env = dict(os.environ, GTKW_COUNT_OUT=out)
        subprocess.run(["xvfb-run", "-a", "gtkwave", "-S", os.path.join(HERE, "gtkw_count.tcl"),
                        "-a", os.path.join(HERE, f"{test}.gtkw"), vcd],
                       env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=300)
        got = -1
        if os.path.exists(out):
            with open(out) as fh:
                m = re.match(r"traces=(\d+)", fh.readline())
                got = int(m.group(1)) if m else -1
    want = nsig + ngroups
    if got != want:
        print(f"WAVE CHECK FAIL: {test}: GTKWave resolved {got} traces, expected {want}")
        return 1
    print(f"  gtkwave load: OK ({got} traces resolved headless)")
    return 0


def main(argv):
    if len(argv) >= 2 and argv[1] == "gen":
        return gen()
    if len(argv) == 4 and argv[1] == "check":
        return check(argv[2], argv[3])
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
